"use client";
import { FormEvent, useState } from "react";
type Certificate={id:string;title:string;organization:string;date:string|null;credentialId:string|null;verificationUrl:string|null;assetUrl:string|null;featured:boolean;skills:string|null;status:"DRAFT"|"PREVIEW"|"PUBLISHED"};
export function CertificateManager({initialCertificates}:{initialCertificates:Certificate[]}) {
 const [rows,setRows]=useState(initialCertificates),[editing,setEditing]=useState<Certificate|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const payload={title:String(f.get("title")||""),organization:String(f.get("organization")||""),date:String(f.get("date")||"")||null,credentialId:String(f.get("credentialId")||"")||null,verificationUrl:String(f.get("verificationUrl")||"")||null,assetUrl:String(f.get("assetUrl")||"")||null,skills:String(f.get("skills")||"")||null,featured:f.get("featured")==="on",status:String(f.get("status")||"DRAFT")};try{const r=await fetch(editing?`/api/certificates/${editing.id}`:"/api/certificates",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save certificate.");const row={...d.certificate,date:d.certificate.date?new Date(d.certificate.date).toISOString():null};setRows(c=>editing?c.map(x=>x.id===row.id?row:x):[row,...c]);setEditing(null);e.currentTarget.reset()}catch(x){setError(x instanceof Error?x.message:"Could not save certificate.")}finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("Delete this certificate?"))return;setBusy(true);setError("");try{const r=await fetch(`/api/certificates/${id}`,{method:"DELETE"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not delete certificate.");setRows(c=>c.filter(x=>x.id!==id));if(editing?.id===id)setEditing(null)}catch(x){setError(x instanceof Error?x.message:"Could not delete certificate.")}finally{setBusy(false)}}
 return <div className="grid gap-8 lg:grid-cols-[380px_1fr]"><form key={editing?.id??"new"} onSubmit={submit} className="surface space-y-4 p-6"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-blue-400">Credential editor</p><h2 className="mt-2 text-xl font-semibold">{editing?"Edit certificate":"Add certificate"}</h2></div>
 <label className="grid gap-2 text-sm">Title<input name="title" required maxLength={200} defaultValue={editing?.title||""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Organization<input name="organization" required maxLength={180} defaultValue={editing?.organization||""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Date<input name="date" type="date" defaultValue={editing?.date?editing.date.slice(0,10):""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Credential ID<input name="credentialId" maxLength={160} defaultValue={editing?.credentialId||""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Verification URL<input name="verificationUrl" type="url" maxLength={1000} defaultValue={editing?.verificationUrl||""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Asset URL<input name="assetUrl" type="url" maxLength={1000} defaultValue={editing?.assetUrl||""} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label><label className="grid gap-2 text-sm">Related skills<input name="skills" maxLength={2000} defaultValue={editing?.skills||""} placeholder="React, TypeScript, SQL" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/></label>
 <div className="grid gap-2 text-sm"><label className="flex items-center gap-2"><input name="featured" type="checkbox" defaultChecked={editing?.featured??false}/> Featured</label><label className="flex items-center gap-2">Status<select name="status" defaultValue={editing?.status||"DRAFT"} className="ml-auto rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"><option>DRAFT</option><option>PREVIEW</option><option>PUBLISHED</option></select></label></div>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<div className="flex gap-2"><button disabled={busy} className="btn btn-primary" type="submit">{busy?"Saving…":editing?"Save changes":"Add certificate"}</button>{editing&&<button type="button" className="btn" onClick={()=>setEditing(null)}>Cancel</button>}</div></form>
 <div className="grid gap-4">{rows.length===0?<div className="surface border-dashed p-10 text-center text-slate-500">No certificates yet.</div>:rows.map(row=><article key={row.id} className="surface p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-lg font-semibold">{row.title}</h3><p className="mt-1 text-sm text-slate-400">{row.organization}{row.date?` · ${new Date(row.date).toLocaleDateString()}`:""}</p><p className="mt-2 text-xs text-slate-500">{row.status}{row.featured?" · Featured":""}{row.credentialId?` · ${row.credentialId}`:""}</p></div><div className="flex gap-2"><button className="btn text-sm" onClick={()=>setEditing(row)}>Edit</button><button className="btn text-sm text-red-300" onClick={()=>remove(row.id)}>Delete</button></div></div>{row.verificationUrl&&<a className="mt-4 inline-block text-sm text-blue-300" href={row.verificationUrl} target="_blank" rel="noreferrer">Verify credential ↗</a>}</article>)}</div></div>
}
