"use client";
import { FormEvent,useState } from "react";
type Interview={id:string;company:string;role:string;dateTime:string;applicationId:string|null;round:string|null;interviewer:string|null;type:string|null;meetingLink:string|null;prepNotes:string|null;questions:string|null;notes:string|null;feedback:string|null;result:string|null;nextRound:string|null};
type Application={id:string;company:string;jobTitle:string};
export function InterviewManager({initialInterviews,applications}:{initialInterviews:Interview[];applications:Application[]}){
const [rows,setRows]=useState(initialInterviews),[editing,setEditing]=useState<Interview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const local=String(f.get("dateTime")||"");const payload={company:String(f.get("company")||""),role:String(f.get("role")||""),dateTime:new Date(local).toISOString(),applicationId:String(f.get("applicationId")||"")||null,round:String(f.get("round")||"")||null,interviewer:String(f.get("interviewer")||"")||null,type:String(f.get("type")||"")||null,meetingLink:String(f.get("meetingLink")||"")||null,prepNotes:String(f.get("prepNotes")||"")||null,questions:String(f.get("questions")||"")||null,notes:String(f.get("notes")||"")||null,feedback:String(f.get("feedback")||"")||null,result:String(f.get("result")||"")||null,nextRound:String(f.get("nextRound")||"")?new Date(String(f.get("nextRound"))).toISOString():null};try{const r=await fetch(editing?"/api/dashboard/interviews/"+editing.id:"/api/dashboard/interviews",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not save interview.");setRows(x=>editing?x.map(i=>i.id===d.id?d:i):[d,...x]);setEditing(null);e.currentTarget.reset();}catch(err){setError(err instanceof Error?err.message:"Could not save interview.");}finally{setBusy(false);}}
async function remove(id:string){if(!window.confirm("Delete this interview?"))return;setBusy(true);try{const r=await fetch("/api/dashboard/interviews/"+id,{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not delete interview.");setRows(x=>x.filter(i=>i.id!==id));}catch(err){setError(err instanceof Error?err.message:"Could not delete interview.");}finally{setBusy(false);}}
const field="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2";
return <div className="grid gap-8 lg:grid-cols-[380px_1fr]"><form key={editing?.id||"new"} onSubmit={save} className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/40 p-6"><div><p className="text-xs uppercase tracking-[0.2em] text-blue-400">Interview workspace</p><h2 className="mt-2 text-xl font-semibold">{editing?"Edit interview":"Schedule interview"}</h2></div>
<label className="grid gap-2 text-sm">Company<input name="company" required defaultValue={editing?.company||""} className={field}/></label><label className="grid gap-2 text-sm">Role<input name="role" required defaultValue={editing?.role||""} className={field}/></label><label className="grid gap-2 text-sm">Date & time<input name="dateTime" type="datetime-local" required defaultValue={editing?new Date(editing.dateTime).toISOString().slice(0,16):""} className={field}/></label>
<label className="grid gap-2 text-sm">Application<select name="applicationId" defaultValue={editing?.applicationId||""} className={field}><option value="">Standalone</option>{applications.map(a=><option value={a.id} key={a.id}>{a.company+" · "+a.jobTitle}</option>)}</select></label>
<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Round<input name="round" defaultValue={editing?.round||""} className={field}/></label><label className="grid gap-2 text-sm">Type<input name="type" placeholder="Technical, HR..." defaultValue={editing?.type||""} className={field}/></label></div><label className="grid gap-2 text-sm">Interviewer<input name="interviewer" defaultValue={editing?.interviewer||""} className={field}/></label><label className="grid gap-2 text-sm">Meeting link<input name="meetingLink" type="url" defaultValue={editing?.meetingLink||""} className={field}/></label>
{(["prepNotes","questions","notes","feedback"] as const).map(n=><label key={n} className="grid gap-2 text-sm">{n==="prepNotes"?"Prep notes":n[0].toUpperCase()+n.slice(1)}<textarea name={n} rows={3} defaultValue={editing?.[n]||""} className={field}/></label>)}<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Result<input name="result" defaultValue={editing?.result||""} className={field}/></label><label className="grid gap-2 text-sm">Next round<input name="nextRound" type="datetime-local" defaultValue={editing?.nextRound?new Date(editing.nextRound).toISOString().slice(0,16):""} className={field}/></label></div>
{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<div className="flex gap-2"><button disabled={busy} className="rounded-lg bg-blue-500 px-4 py-2 text-sm font-medium disabled:opacity-50">{busy?"Saving…":editing?"Save changes":"Add interview"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Cancel</button>}</div></form>
<div className="grid gap-4">{rows.length?rows.map(x=><article key={x.id} className="rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">{x.company+" · "+x.role}</h3><p className="mt-1 text-sm text-slate-400">{(x.round||"Interview")+(x.type?" · "+x.type:"")+(x.interviewer?" · "+x.interviewer:"")}</p></div><time className="text-sm text-blue-400">{new Date(x.dateTime).toLocaleString()}</time></div>{x.prepNotes&&<p className="mt-3 text-sm text-slate-500">Prep: {x.prepNotes}</p>}<div className="mt-4 flex gap-2">{x.meetingLink&&<a href={x.meetingLink} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Join ↗</a>}<button onClick={()=>setEditing(x)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">Edit</button><button disabled={busy} onClick={()=>remove(x.id)} className="rounded-lg border border-red-900/50 px-3 py-2 text-xs text-red-300">Delete</button></div></article>):<div className="rounded-2xl border border-dashed border-slate-800 p-10 text-center text-slate-500">No interviews scheduled.</div>}</div></div>}